"Quora vimrc
so ~/vim/config/qvimrc
so ~/vim/config/mac_vimrc "enabled for macs

"Pathogen 
execute pathogen#infect()
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

"Miscelanneous
set hlsearch                                "highlight search
set hidden                                  "store buffer edit history

"Copy + pasta
vnoremap <C-x> "+x
vnoremap <C-c> "+y
map <C-V> "+gP
cmap <C-V> <C-R>+

"Double click search
noremap <2-LeftMouse> *
inoremap <2-LeftMouse> <c-o>*

"Buffered explorer config
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1 

"Syntastic config TODO: TOO SLOW
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_check_on_open = 1          "toggle this to turn on flake8

"For cleaning out vim swap files
"set backupdir=./.backup,.,/tmp
"set directory=.,./.backup,/tmp

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
nnoremap <leader>. :CtrlPTag<cr>
nnoremap <silent> <Leader>b :TagbarToggle<CR>

" https://www.mattlayman.com/blog/2019/supercharging-vim-blazing-fast-search/
let g:rg_command = 'rg --vimgrep -S -L'
let g:rg_highlight = 1
let g:rg_derive_root = 0

" https://vim.fandom.com/wiki/Search_for_current_word_in_multiple_files
" by default, do not search tests directories
nnoremap rg :Rg <cword> --type-add 'tests:*tests.py' --type-not tests .<CR>
" this command searches inclusive of test files
nnoremap rt :Rg <cword> .<CR>

" vim black and black-macchiato setup
let g:black_linelength = 120
autocmd FileType python vnoremap <buffer> <Leader>f <plug>(BlackMacchiatoSelection)
autocmd FileType python nnoremap <buffer> <Leader>f <plug>(BlackMacchiatoCurrentLine)
