"Quora vimrc
so ~/vim/config/qvimrc
"so ~/vim/config/mac_vimrc "enabled for macs

"Taglist config
let Tlist_Ctags_Cmd = "/home/naranb/bin/ctags"
let Tlist_WinWidth = 50
map <F4> :TlistToggle<cr>                                                                              
"Toggle between mac and linux
map <F8> :!/home/naranb/bin/ctags -R .<CR>
"map <F8> :!/Users/Naran/bin/ctags -R .<CR>

let Tlist_Auto_Highlight_tag = 1
let Tlist_Auto_Open = 0
let Tlist_Auto_update = 1
let Tlist_Use_Right_Window = 1
let Tlist_Compact_Format = 1
let Tlist_Show_One_File = 1
let Tlist_Enable_Fold_Column = 0
let Tlist_Exit_OnlyWindow = 1
let Tlist_GainFocus_On_ToggleOpen = 1

"Pathogen 
execute pathogen#infect()
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

"Command-T
"replace default selection to tab
"let g:CommandTSelectPrevMap = ['<C-p>', '<C-k>', '<Up>', '<C-Up>', '<']
"let g:CommandTSelectNextMap = ['<C-n>', '<C-j>', '<Down>', '<C-Down>', '>']
"let g:CommandTAcceptSelectionMap = '<C-CR>'
"let g:CommandTAcceptSelectionSplitMap = '<C-s>'
"let g:CommandTAcceptSelectionTabMap = ['<CR>', '<C-t>']

" Needed for using vim in screen
"set term=xterm

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

"Miscelanneous
set hlsearch                                "highlight search
set guifont=Bitstream\ Vera\ Sans\ Mono\ 11 "font size
set hidden                                  "store buffer edit history

"Copy + pasta
vnoremap <C-x> "+x
vnoremap <C-c> "+y
map <C-V> "+gP
cmap <C-V> <C-R>+

"Double click search
noremap <2-LeftMouse> *
inoremap <2-LeftMouse> <c-o>*

"Buffered explorer config
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1 

"Syntastic config TODO: TOO SLOW
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_check_on_open = 1          "toggle this to turn on flake8

"For cleaning out vim swap files
"set backupdir=./.backup,.,/tmp
"set directory=.,./.backup,/tmp


" New tab
nnoremap <silent> <C-t> :tabnew<CR>
vnoremap <silent> <C-t> :tabnew<CR>
inoremap <silent> <C-t> <Esc>:tabnew<CR>

" Close tab
nnoremap <silent> <C-w> :tabclose<CR>
vnoremap <silent> <C-w> :tabclose<CR>
inoremap <silent> <C-w> <Esc>:tabclose<CR>

" Switch tabs
" note that this is mapped to <C-{> and <C-}> because
" AutoKey already maps <C-{> to <C-S-tab>
nnoremap <silent> <C-S-tab> :tabprevious<CR>
nnoremap <silent> <C-tab> :tabnext<CR>
vnoremap <silent> <C-S-tab> :tabprevious<CR>
vnoremap <silent> <C-tab> :tabnext<CR>
inoremap <silent> <C-S-tab> :tabprevious<CR>
inoremap <silent> <C-tab> :tabnext<CR>
" backup switch tabs shortcut
nnoremap <silent> <C-Left> :tabprevious<CR>
nnoremap <silent> <C-Right> :tabnext<CR>
vnoremap <silent> <C-Left> :tabprevious<CR>
vnoremap <silent> <C-Right> :tabnext<CR>
inoremap <silent> <C-Left> :tabprevious<CR>
inoremap <silent> <C-Right> :tabnext<CR>


" Switching buffers
" left
inoremap <silent> <C-h> <esc><C-W>h
vnoremap <silent> <C-h> <esc><C-W>h
nnoremap <silent> <C-h> <C-W>h

" down
inoremap <silent> <C-j> <esc><C-W>j
vnoremap <silent> <C-j> <esc><C-W>j
nnoremap <silent> <C-j> <C-W>j

" right
inoremap <silent> <C-l> <esc><C-W>l
vnoremap <silent> <C-l> <esc><C-W>l
nnoremap <silent> <C-l> <C-W>l

" up
inoremap <silent> <C-k> <esc><C-W>k
vnoremap <silent> <C-k> <esc><C-W>k
nnoremap <silent> <C-k> <C-W>k

" re-map escape: need this due to interaction with AutoKey
nnoremap <silent> <A-Left> <esc>

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
